name: "Greet With A Random Joke"
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: setup environment
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: mast joke mara
        uses: deep5050/MastJokeMara@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issue_msg: |
            Hi, {{author}} here is a joke for you 
            {{joke}}
          
          PR_msg: |
            Hi, {{author}} here is a joke for you 
            {{joke}}
